### ISSUE TITLE
Create new seqr deployment for reanalysis project

### ISSUE THREAD

**Issue by illusional** [populationgenomics/seqr#118]
- [x] Rename `dev` to `staging` + update credentials
- [x] Create new database `seqrdb-reanalysis-dev` + new credentials
- [x] Generate new elasticsearch credentials
- [x] Create new deployment of seqr (called `reanalysis-dev`) https://github.com/populationgenomics/seqr/pull/119#pullrequestreview-893199226
- [x] Create branch `reanalysis-dev` that deploys to new cloud run instance (by updating GH action)

**Comment by lgruen** [comment]
I think this is all done, just waiting for the new subdomain DNS entry to become visible, so we can issue a HTTPS certificate for the load balancer endpoint.

Reassigning to @illusional for the Postgres database creation.
