### ISSUE TITLE
hg19 coordinates and links broken in CIRCA project

### ISSUE THREAD

**Issue by mathob** [populationgenomics/seqr#129]
**Describe the bug**
After a variant search in CIRCA each variant incorrectly shows the hg19 position as identical to the hg38 position

Also the hg19 link to UCSC browser doesn't work:
Sorry, couldn't locate chrchr19:14755107-14755127 in Human Feb. 2009 (GRCh37/hg19)

**Link to page(s) where bug is occurring**
search for e.g.  19-14755117-G-A
https://seqr.populationgenomics.org.au/variant_search/results/e6d64936528ea23da0f8bbcc43e737f8?page=1&sort=xpos

**Scope of the bug**
Are you experiencing this issue in all projects? Within specific families within one project?
just CIRCA not NA12878

**Screenshots**

![image](https://user-images.githubusercontent.com/56565998/161203991-321907fc-93c0-4351-8040-849a5d19162e.png)

**Comment by vladsaveliev** [comment]
Batch backend doesn't support liftover, so I moved lifting over to dataproc, and it should be fixed in the new round of seqr loader.

Example of the validation dataset with fixed coordinates: https://seqr.populationgenomics.org.au/project/R0019_validation/project_page

**Comment by vladsaveliev** [comment]
FYI - I removed myself from the assignees because this should be solved. Leaving closing the issue to the topic starter.
