### ISSUE TITLE
IGV is broken

### ISSUE THREAD

**Issue by lgruen** [populationgenomics/seqr#69]
IGV used to work in our deployment (https://centrepopgen.slack.com/archives/C01R7CKJGHM/p1617779770139100), but it seems to have broken with a relatively recent merge (https://centrepopgen.slack.com/archives/C022X7KRUBU/p1626161589174300).

The JS dev console shows a `Content Security Policy directive: "connect-src self"` issue when trying to load `https://igv.org/genomes/genomes.json`:
<img width="1920" alt="CleanShot 2021-07-13 at 17 32 36@2x" src="https://user-images.githubusercontent.com/2876012/125541447-2894137e-6b80-4d54-8423-18f73baff64a.png">

**Comment by illusional** [comment]
Closing as fixed by #73.
