### ISSUE TITLE
JS errors when using Firefox

### ISSUE THREAD

**Issue by lgruen** [populationgenomics/seqr#70]
When accessing seqr through Firefox, there are a lot of JS errors, leading to a blank page: https://centrepopgen.slack.com/archives/C022X7KRUBU/p1626218042175700?thread_ts=1626134227.162900&cid=C022X7KRUBU

It seems to work better with Chrome. Given that some of the errors are related to `Content Security Policy: Couldn't process unknown directive 'style-src-elem'`, this might well be a duplicate of #69.

**Comment by illusional** [comment]
Closing as resolved by #73.
