### ISSUE TITLE
Disentangle dev from prod environments

### ISSUE THREAD

**Issue by lgruen** [populationgenomics/seqr#72]
Currently, the dev frontend uses the same Postgres DB and Elasticsearch instance as prod. We should isolate dev from prod better: have separate users both Postgres and Elasticsearch, so prod data can't be read at all from the dev instance. Furthermore the loading pipeline should only be able to modify dev data when using the `test` access level and require the `standard` access level to write to prod.

**Comment by illusional** [comment]
I've started working through this, for now:
- I've created a separate database for the `seqr-dev` instance, and loaded the NA12878 trio.

This is a good first step towards disentangling from a data point of view, it allow us to test migrations for new versions correctly, and modifications made to this won't reflect in the production instance.

**Comment by illusional** [comment]
This was disentangled more as part of https://github.com/populationgenomics/seqr/pull/161
