### ISSUE TITLE
Change saved search parameters

### ISSUE THREAD

**Issue by danielreti** [populationgenomics/seqr#74]
Increase Callset AF filter to 0.1 for De Novo and Recessive saved searches.
Original settings: De Novo (0.01) and Recessive (0.03). 
Changes are made to `variant_searches.json` and updated with `python -u manage.py loaddata variant_searches`

This raised threshold is a response to the low number of samples in the Acute Care project, and should be decreased back to their original values once more samples are added.

**Comment by illusional** [comment]
Released.
