### ISSUE TITLE
Dan Pavlic test - can delete immediately 

### ISSUE THREAD

**Issue by danielpavlic** [populationgenomics/seqr#75]
**Describe the bug**
A clear and concise description of what the bug is, and what you instead expect to be happening

**Link to page(s) where bug is occurring**
https://seqr.populationgenomics.org.au/...

**Scope of the bug**
Are you experiencing this issue in all projects? Within specific families within one project?

**Screenshots**

**Comment by illusional** [comment]
Hi @danielpavlic, unfortunately we could not replicate your issue, could you provide more details and attach a screenshot. I'll close this issue for now, but feel free to reopen if it persists.
